version: '2'

services:
  config-server:
    image: olivercw/pet-conf:dev
    container_name: config-server
    mem_limit: 512M
    ports:
      - 8888:8888

  discovery-server:
    image: olivercw/pet-disco:dev
    container_name: discovery-server
    mem_limit: 512M
    ports:
      - 8761:8761
    depends_on:
      - config-server
    entrypoint: ["./dockerize", "-wait=tcp://config-server:8888", "-timeout=160s", "--", "java", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]

  customers-service:
    image: olivercw/pet-custo:dev
    container_name: customers-service
    mem_limit: 512M
    ports:
     - 8081:8081
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./dockerize", "-wait=tcp://discovery-server:8761", "-timeout=160s", "--", "java", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar" ]

  visits-service:
    image: olivercw/pet-visit:dev
    container_name: visits-service
    mem_limit: 512M
    ports:
     - 8082:8082
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./dockerize", "-wait=tcp://discovery-server:8761", "-timeout=160s", "--", "java", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar" ]

  vets-service:
    image: olivercw/pet-vet:dev
    container_name: vets-service
    mem_limit: 512M
    ports:
     - 8083:8083
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./dockerize", "-wait=tcp://discovery-server:8761", "-timeout=160s", "--", "java", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar" ]

  api-gateway:
    image: olivercw/pet-api:dev
    container_name: api-gateway
    mem_limit: 512M
    ports:
     - 8085:8080
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./dockerize", "-wait=tcp://discovery-server:8761", "-timeout=160s", "--", "java", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar" ]

  admin-server:
    image: olivercw/pet-admn:dev
    container_name: admin-server
    mem_limit: 512M
    ports:
     - 9090:9090
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./dockerize", "-wait=tcp://discovery-server:8761", "-timeout=160s", "--", "java", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar" ]

  hystrix-dashboard:
    image: olivercw/pet-hyst:dev
    container_name: hystrix-dashboard
    mem_limit: 512M
    ports:
     - 7979:7979
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./dockerize", "-wait=tcp://discovery-server:8761", "-timeout=160s", "--", "java", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar" ]

  tracing-server:
    image: openzipkin/zipkin
    container_name: tracing-server
    mem_limit: 512M
    ports:
     - 9411:9411

  grafana-server:
    image: olivercw/pet-graf:dev
    container_name: grafana-server
    mem_limit: 256M
    ports:
    - 3000:3000

  prometheus-server:
    image: olivercw/pet-prom:dev
    container_name: prometheus-server
    mem_limit: 256M
    ports:
    - 9091:9090

  mysql-server:
    image: mysql:5.7.8
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: petclinic
      MYSQL_DATABASE: petclinic
    mem_limit: 256M
    ports:
    - 3306:3306